// get all states from db
GET http://localhost:3000/states/
###

//get state detials with state id
GET http://localhost:3000/states/8/
###

//add district details to district table in db
POST http://localhost:3000/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

//get district details with district id 
GET http://localhost:3000/districts/322/
###

//remove district from database
DELETE http://localhost:3000/districts/322/
###

//update district details in database
PUT http://localhost:3000/districts/1/
Content-Type:application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

// get cases stats from districts
GET http://localhost:3000/states/12/stats/
###

// get state name with district id
GET http://localhost:3000/districts/1/details/
###